// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  /////////////////////////////////////////////////////////////////////////////
  // Replace with your code 
  vec3 N = normalize(normal_fs_in);
  vec3 P = view_pos_fs_in.xyz;
  vec3 V = normalize(-P);

  float omega  = 2.0 * M_PI / 8.0;
  float theta  = animation_seconds * omega;
  float radius = 2.5;

  vec3 light_pos_world = vec3(radius * cos(theta), 2.0, radius * sin(theta));
  vec3 Lpos = (view * vec4(light_pos_world, 1.0)).xyz;
  vec3 L    = normalize(Lpos - P);


  //material
  vec3 ka = vec3(0.1);
  vec3 ks = vec3(0.60);
  vec3 kd = vec3(1.0);
  float p = 400.0;
  
  float lat = clamp(sphere_fs_in.y, -1.0, 1.0);
  float t = 0.5 * (lat + 1.0);

  float freq = 10.0;

  float n = perlin_noise(8.0 * sphere_fs_in);
  t += 0.1 * n;

  float rings = 0.5 + 0.5 * sin(2.0 * M_PI * freq * t);

  vec3 cLo = vec3(0.05, 0.05, 0.2);
  vec3 cHi = vec3(0.2, 0.2, 1.0);
  kd = mix(cLo, cHi, rings);

  if (is_moon) {
    kd = kd + vec3(0.0, 0.0, -0.5);

  } else {
    kd = kd + vec3(0.0, 0.0, 0.5);
    
  }
  color = blinn_phong(ka, kd, ks, p, N, V, L);
  /////////////////////////////////////////////////////////////////////////////
}
